server:
  port: 3000
spring:
  datasource:
    username: admin
    password: X3reWQr2fdoFTItqE4kOIMyhoo81Uerr6xAL9syW/CWSaWRGnORcnjq+XMJ/4dDBUxr7B67OJr0ybC9oMVORyw==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.152.209.169:3306/jc-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true

logging:
  config: classpath:log4j2-spring.xml

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK6asWdwagGuu0mstNGTw8uDxWBGLDLAzmLdru1cLmjni5BOn0ohJjCcrcXGnt4Bo7FmwGCrEY/fwfGvMzz0eFUCAwEAAQ==





