server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss # 路由的唯一标识符
          uri: lb://club-oss # 指定路由的目标 URI。lb:// 前缀表示应使用负载均衡器，club-oss 是服务 ID
          predicates:
            - Path=/oss/** #此断言匹配任何以 /oss/ 开头的请求路径
          filters:
            - StripPrefix=1 # 去掉请求路径中的第一个路径元素 如请求/oss/club-oss/getAllBuckets，去掉后为/oss/getAllBuckets
        - id: auth
          uri: lb://club-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://club-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1
    # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 8.152.209.169
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: club123456
    # 连接超时时间
    timeout: 3s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
